export const API_ENDPOINTS = {
    //auth service
    SignUp: '/sign-up',
    SignIn: '/sign-in',
    VerifyMail: '/verify-email',
    Upload: '/file-upload',
    PrivacyPolicy: '/signin',
    SendPasswordReset: '/send-password-reset',
    ResetPassword: '/reset-password',
    CountryList: '/country',
    OrgOnboard: '/onboard-organization',
    OrgResubmit: '/update-organization',
    ME: '/get-user-profile',
    Projects: '/projects',
    cart: '/cart-negotiation',
    order: '/create-order',
    buyer_update_negotiation: '/negotiation-counteroffer-buyer',
    seller_update_negotiation: '/negotiation-counteroffer-seller',
    get_seller_negotiation_projects: '/get-negotiation-seller-list',
    ChangePassword: '/change-password',
    BankList: '/organization/bank-details',
    ProjectAgreement: `/agreement-token`,
    AgreementSubmit: (token: string | string[] | undefined) => `/agreement-update?token=${token}`,
    // ProjectList: '/get-seller-project-list/1',
    // SellerOrderList: '/get-seller-order-list/1',
    // BuyerOrderList: '/get-buyer-order-list/1',
    Address: 'organization/addresses',
    ICRAuth: 'icr-oauth',

    //project service
    Dashboard: '/dashboard',
    ResendVerificationMail: '/resend-verification-mail',
    ProjectStatus: '/project-statuses',
    deleteCart: '/delete-to-cart',

    //project Stepper
    SubmitProject: '/test',
    ProjectInit: "/project-init",
    SellerStats: "/get-seller-order-stats",
    BuyerStats: "/get-buyer-order-stats",
    DocumentNeedToUpload: (projectId: string) => `/project-status/${projectId}/documents`,
    BuyerOrderList: (status: number, page: number) => `/get-buyer-order-list/${status}?page=${page}&limit=10`,
    SellerOrderList: (status: number, page: number) => `/get-seller-order-list/${status}?page=${page}&limit=10`,
    SellerNegotiation: (status: number, page: number) => `/get-negotiation-seller-list/${status}?page=${page}&limit=10`,
    BuyerNegotiation: (status: number, page: number) => `/get-negotiation-buyer-list/${status}?page=${page}&limit=10`,
    ProjectList: (status: number, page: number) => `/get-seller-project-list/${status}?page=${page}&limit=10`,
    ProjectUpdate: (projectId: string) => `/update/${projectId}`,
    ProjectCurrentStatus: (projectId: string | null) => `/beta/${projectId}`,
    Promotion: (token: string | null) => `/get-campaign-token?token=${token}`,
    ShowIntent: (token: string | null) => `/project-intent?token=${token}`,


};
